name: Build Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Android Workload
      run: dotnet workload install android

    - name: Build Debug
      run: dotnet build /p:Platform="x64" --configuration Android_Debug
    - name: Build Release
      run: dotnet build /p:Platform="x64" --configuration Android_Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
