name: Android [Debug]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_dev_release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        
    - name: Install Android Workload
      run: dotnet workload install android
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build Debug
      run: dotnet build /p:Platform="x64" --configuration Android_Debug
    
   # - name: Build Release
    #  run: dotnet build /p:Platform="x64" --configuration Android_Release
    
    - name: Create Release
      id: build_dev_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Latest-Dev
        release_name: Latest Dev
        body: |
          This is the latest development build.
        draft: false
        prerelease: false
        
    - name: Publish Release
      id: publish_release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./dist/molten-latest-dev.zip
        asset_name: molten-latest-dev.zip
        asset_content_type: application/zip
