name: Generate Changelog
on: [workflow_run]

jobs:
  Get-Changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Log
        run: git log --pretty="[%h]"
