name: Generate changelog
on:
  pull_request:
    types: [ opened ]

  # Optionally you can use `workflow_dispatch` to run Changelog CI Manually
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true
      fetch_depth:
        description: 'Changelog commit depth'
        required: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ github.event.inputs.fetch_depth }}
    - uses: BobAnkh/auto-generate-changelog@v1
      with:
        REPO_NAME: 'Syncaidius/MoltenEngine'
        BRANCH: 'master'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG_{{ github.event.inputs.release_version }}.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): Updated {{ github.event.inputs.release_version }} release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
