name: Generate changelog
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.3
      with:
        REPO_NAME: 'Syncaidius/MoltenEngine'
        BRANCH: 'master'
        ACCESS_TOKEN: ${{secrets.ACCESSTOKEN}}
        PATH: 'CHANGELOG_${{ github.event.inputs.release_version }}.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): Updated ${{ github.event.inputs.release_version }} release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
